import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f9a8deaa-87f2-4191-92b8-c7661aae48de/air-monarch-iv-mens-workout-shoes-p8qNlT.png",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "80",
    company: "Nike",
    color: "white",
    category: "sneakers",
    description: "Enjoy exercising in the versatile Nike Men's Air Monarch IV Lightweight Training Shoes. The shoes feature leather uppers for durability and support, and the solid rubber outsoles provide excellent traction for your training needs.  ",
    options: ["https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d43b949c-246a-4964-8a5c-23f354a4e542/air-monarch-iv-mens-workout-shoes-p8qNlT.png",
              "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7869dac9-4d4a-4337-9c13-affa8c0d3c5c/air-monarch-iv-mens-workout-shoes-p8qNlT.png",
            "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/f9a8deaa-87f2-4191-92b8-c7661aae48de/air-monarch-iv-mens-workout-shoes-p8qNlT.png"],
    id: 1,
  },
  {
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/81f05e44-e163-47f7-9610-3cdb8f06bacd/air-vapormax-plus-mens-shoe-nC0dzF.png",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "180",
    company: "Nike",
    color: "black",
    category: "sneakers",
    options: ['https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/i1-8fd42049-6938-45f4-ae2a-e002658811d5/air-vapormax-plus-chicago-mens-shoes-nC0dzF.png',
              'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/fbc7e2fc-e93b-4a0d-aa88-92c6bb961399/air-vapormax-plus-mens-shoes-nC0dzF.png',
            "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/81f05e44-e163-47f7-9610-3cdb8f06bacd/air-vapormax-plus-mens-shoe-nC0dzF.png"],
    id: 2,
  },

  {
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d616260a-0a8e-48b1-b5c5-e155b990acb8/waffle-one-mens-shoes-4SPCK4.png",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "80",
    company: "Nike",
    color: "beige",
    category: "sneakers",
    options: ['https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/8630e7b1-e2a2-4591-904f-d6f6257682b1/waffle-one-se-mens-shoe-4SPCK4.png',
              'https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/7903e483-c4e7-4fbf-8259-f265b1641c3f/waffle-one-mens-shoes-4SPCK4.png',
            "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/d616260a-0a8e-48b1-b5c5-e155b990acb8/waffle-one-mens-shoes-4SPCK4.png"],
    id: 3,
  },
  {
    img: "https://static.nike.com/a/images/t_PDP_1728_v1/f_auto,q_auto:eco/cc57a5a7-02ee-447c-9903-2b9ce369bcf2/flex-experience-run-12-mens-road-running-shoes-lqThC9.png",
    title: "Nike Flex Experience Run 12",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "75",
    company: "Nike  ",
    color: "beige",
    category: "sneakers",
    options: [],
    id: 4,
  },
  {
    img: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Alessia",
    color: "green",
    category: "flats",
    options: [],
    id: 5,
  },
  {
    img: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Clarks",
    color: "black",
    category: "flats",
    options: [],
    id: 6,
  },

  {
    img: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Robel",
    color: "white",
    category: "flats",
    options: [],
    id: 7,
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    options: [],
    id: 8,
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    newPrice: "200",
    company: "Nike",
    color: "blue",
    category: "sneakers",
    options: [],
    id: 9,
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "PUMA BLACK-OCE",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
    options: [],
    id: 10,
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
    options: [],
    id: 11,
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    title: "Unisex-Adult Super",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    options: [],
    id: 12,
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
    options: [],
    id: 13,
  },
  {
    img: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    options: [],
    id: 14,
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
    options: [],
    id: 15,
  },
  {
    img: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
    title: "Rainbow Chex Skate",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "flats",
    options: [],
    id: 16,
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "flats",
    options: [],
    id: 17,
  },
  {
    img: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
    title: "Vans Unisex Low-Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "blue",
    category: "flats",
    options: [],
    id: 18,
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "flats",
    options: [],
    id: 19,
  },
  {
    img: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Dream Paris",
    color: "black",
    category: "heels",
    options: [],
    id: 20,
  },
  {
    img: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "puma",
    color: "black",
    category: "heels",
    options: [],
    id: 21,
  },
  {
    img: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Dream Paris",
    color: "red",
    category: "heels",
    options: [],
    id: 22,
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    options: [],
    id: 23,
  },

  {
    img: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
    title: "Low Mid Block Heels",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Dream Paris",
    color: "black",
    category: "heels",
    options: [],
    id: 24,
  },
  {
    img: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
    title: "Chunky High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Dream Paris",
    color: "brown",
    category: "heels",
    options: [],
    id: 25,
  },
  {
    img: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
    title: "Amore Fashion Stilettos",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Dream Paris",
    color: "white",
    category: "heels",
    options: [],
    id: 26,
  },
  {
    img: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
    title: "Bridal Sandals Glitter",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Dream Paris",
    color: "black",
    category: "heels",
    options: [],
    id: 27,
  },
  {
    img: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
    title: "Wedding Prom Bridal",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Dream Paris",
    color: "black",
    category: "heels",
    options: [],
    id: 28,
  },
];

export default data;
